package com.spatel.scansign.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val md_theme_light_primary = Color(0xFF1565C0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD4E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C3A)
val md_theme_light_secondary = Color(0xFF00897B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB2DFDB)
val md_theme_light_onSecondaryContainer = Color(0xFF002021)
val md_theme_light_tertiary = Color(0xFFFFA000)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE0B2)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
val md_theme_light_background = Color(0xFFF8F9FD)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFEEF0F8)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)

// Dark Theme
val md_theme_dark_primary = Color(0xFF90CAF9)
val md_theme_dark_onPrimary = Color(0xFF003060)
val md_theme_dark_primaryContainer = Color(0xFF004B95)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_secondary = Color(0xFF80CBC4)
val md_theme_dark_onSecondary = Color(0xFF003735)
val md_theme_dark_secondaryContainer = Color(0xFF00504D)
val md_theme_dark_onSecondaryContainer = Color(0xFFB2DFDB)
val md_theme_dark_tertiary = Color(0xFFFFCC80)
val md_theme_dark_onTertiary = Color(0xFF4A2800)
val md_theme_dark_tertiaryContainer = Color(0xFF6A3C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE0B2)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF2A2D35)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_outlineVariant = Color(0xFF44474E)
val md_theme_dark_error = Color(0xFFEF9A9A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)

// Semantic Colors (for direct use in composables)
val ScanSignBlue = Color(0xFF1565C0)
val ScanSignTeal = Color(0xFF00897B)
val ScanSignAmber = Color(0xFFFFA000)
val ScanSignGreen = Color(0xFF43A047)
val ScanSignRed = Color(0xFFE53935)
val ScanSignPurple = Color(0xFF6A1B9A)
val ScanSignOrange = Color(0xFFE65100)
